### ISSUE TITLE
UI does not update when toggling "done" after editing a todo item

### ISSUE THREAD

**Issue by erinnmclaughlin** [jasontaylordev/RapidBlazor#1]
Hi! First off, thank you for making this -- I've been looking for this kind of example project for a while! This will be a really helpful reference.

Wanted to report a small bug: after focusing on a todo item, the strikethrough formatting doesn't update when toggling between "done" and "not-done" states. I think the simplest fix would be to set the `SelectedItem` to `null` after saving:

https://github.com/jasontaylordev/CleanArchitectureBlazor/compare/main...erinnmclaughlin:CleanArchitectureBlazor:main

I could make a PR if you'd like?

**Comment by jasontaylordev** [comment]
Hi @erinnmclaughlin - you're welcome + thanks for raising this issue. Please raise a PR and I'll push the fix through. Happy coding! 😀
