### ISSUE TITLE
Following Changes to Template

### ISSUE THREAD

**Issue by rswetnam** [jasontaylordev/RapidBlazor#6]
Apologies if this is the wrong place to ask this sort of question.  I am using your template to create a new app which I expect not to finish until the new year.  I would like to update my app as your update your template - e.g.  moving from .NET 6 to 7.  Is there a way that I can automatically get the updates you are making e.g. by cloning your repository - or should I just follow your repository and make the same same changes to my app that I see you making to the repository for your template?

**Comment by jasontaylordev** [comment]
Unfortunately not. If the structure remains largely the same, then you can "upgrade" by copying the new version over the top of the old version and comparing the changes using Git. Sorry, I don't have a better solution for you.
