### ISSUE TITLE
Vertical Slice Arch Template?

### ISSUE THREAD

**Issue by Majestic-Mustang** [jasontaylordev/RapidBlazor#7]
First of all thank you for this template, Jason! 😊

I feel that Clean Arch makes the whole project unnecessarily complex while Vertical Slice Architecture makes the development experience so much easier and cleaner. Fewer folders to look at instead of bunch of layers.

Any chance that you'll create templates using Vertical Slice Arch for Blazor/ MAUI etc.?

Thanks!

**Comment by jasontaylordev** [comment]
No plans at this stage.
